export const tokens = [
  {
    word_id: 122390,
    word_type: 'KNOWN',
    word_position: 1,
    surface_form: '全国',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '全国',
    reading: 'ゼンコク',
    pronunciation: 'ゼンコク'
  },
  {
    word_id: 93100,
    word_type: 'KNOWN',
    word_position: 3,
    surface_form: 'の',
    pos: '助詞',
    pos_detail_1: '連体化',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'の',
    reading: 'ノ',
    pronunciation: 'ノ'
  },
  {
    word_id: 2712350,
    word_type: 'KNOWN',
    word_position: 4,
    surface_form: '子供',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '子供',
    reading: 'コドモ',
    pronunciation: 'コドモ'
  },
  {
    word_id: 160990,
    word_type: 'KNOWN',
    word_position: 6,
    surface_form: 'たち',
    pos: '名詞',
    pos_detail_1: '接尾',
    pos_detail_2: '一般',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'たち',
    reading: 'タチ',
    pronunciation: 'タチ'
  },
  {
    word_id: 92920,
    word_type: 'KNOWN',
    word_position: 8,
    surface_form: 'が',
    pos: '助詞',
    pos_detail_1: '格助詞',
    pos_detail_2: '一般',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'が',
    reading: 'ガ',
    pronunciation: 'ガ'
  },
  {
    word_id: 100,
    word_type: 'UNKNOWN',
    word_position: 9,
    surface_form: 'YouTube',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '*'
  },
  {
    word_id: 92910,
    word_type: 'KNOWN',
    word_position: 16,
    surface_form: 'から',
    pos: '助詞',
    pos_detail_1: '格助詞',
    pos_detail_2: '一般',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'から',
    reading: 'カラ',
    pronunciation: 'カラ'
  },
  {
    word_id: 110,
    word_type: 'UNKNOWN',
    word_position: 18,
    surface_form: 'mp3',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '*'
  },
  {
    word_id: 91990,
    word_type: 'KNOWN',
    word_position: 21,
    surface_form: 'で',
    pos: '助詞',
    pos_detail_1: '格助詞',
    pos_detail_2: '一般',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'で',
    reading: 'デ',
    pronunciation: 'デ'
  },
  {
    word_id: 2637240,
    word_type: 'KNOWN',
    word_position: 22,
    surface_form: '落とし',
    pos: '動詞',
    pos_detail_1: '自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '五段・サ行',
    conjugated_form: '連用形',
    basic_form: '落とす',
    reading: 'オトシ',
    pronunciation: 'オトシ'
  },
  {
    word_id: 23430,
    word_type: 'KNOWN',
    word_position: 25,
    surface_form: 'た',
    pos: '助動詞',
    pos_detail_1: '*',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '特殊・タ',
    conjugated_form: '基本形',
    basic_form: 'た',
    reading: 'タ',
    pronunciation: 'タ'
  },
  {
    word_id: 2785240,
    word_type: 'KNOWN',
    word_position: 26,
    surface_form: '音楽',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '音楽',
    reading: 'オンガク',
    pronunciation: 'オンガク'
  },
  {
    word_id: 92880,
    word_type: 'KNOWN',
    word_position: 28,
    surface_form: 'を',
    pos: '助詞',
    pos_detail_1: '格助詞',
    pos_detail_2: '一般',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'を',
    reading: 'ヲ',
    pronunciation: 'ヲ'
  },
  {
    word_id: 467100,
    word_type: 'KNOWN',
    word_position: 29,
    surface_form: 'ナイトコア',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '*',
    reading: '*',
    pronunciation: '*'
  },
  {
    word_id: 92030,
    word_type: 'KNOWN',
    word_position: 34,
    surface_form: 'に',
    pos: '助詞',
    pos_detail_1: '格助詞',
    pos_detail_2: '一般',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'に',
    reading: 'ニ',
    pronunciation: 'ニ'
  },
  {
    word_id: 3011810,
    word_type: 'KNOWN',
    word_position: 35,
    surface_form: 'し',
    pos: '動詞',
    pos_detail_1: '自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: 'サ変・スル',
    conjugated_form: '連用形',
    basic_form: 'する',
    reading: 'シ',
    pronunciation: 'シ'
  },
  {
    word_id: 3691620,
    word_type: 'KNOWN',
    word_position: 36,
    surface_form: 'まくっ',
    pos: '動詞',
    pos_detail_1: '非自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '五段・ラ行',
    conjugated_form: '連用タ接続',
    basic_form: 'まくる',
    reading: 'マクッ',
    pronunciation: 'マクッ'
  },
  {
    word_id: 1114670,
    word_type: 'KNOWN',
    word_position: 39,
    surface_form: 'て',
    pos: '動詞',
    pos_detail_1: '非自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '一段',
    conjugated_form: '連用形',
    basic_form: 'てる',
    reading: 'テ',
    pronunciation: 'テ'
  },
  {
    word_id: 23430,
    word_type: 'KNOWN',
    word_position: 40,
    surface_form: 'た',
    pos: '助動詞',
    pos_detail_1: '*',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '特殊・タ',
    conjugated_form: '基本形',
    basic_form: 'た',
    reading: 'タ',
    pronunciation: 'タ'
  },
  {
    word_id: 563120,
    word_type: 'KNOWN',
    word_position: 41,
    surface_form: '最強',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '最強',
    reading: 'サイキョウ',
    pronunciation: 'サイキョー'
  },
  {
    word_id: 93100,
    word_type: 'KNOWN',
    word_position: 43,
    surface_form: 'の',
    pos: '助詞',
    pos_detail_1: '連体化',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: 'の',
    reading: 'ノ',
    pronunciation: 'ノ'
  },
  {
    word_id: 1820920,
    word_type: 'KNOWN',
    word_position: 44,
    surface_form: '時代',
    pos: '名詞',
    pos_detail_1: '一般',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '*',
    conjugated_form: '*',
    basic_form: '時代',
    reading: 'ジダイ',
    pronunciation: 'ジダイ'
  },
  {
    word_id: 3324130,
    word_type: 'KNOWN',
    word_position: 46,
    surface_form: 'あるの',
    pos: '動詞+名詞',
    pos_detail_1: '自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '五段・ラ行',
    conjugated_form: '基本形',
    basic_form: 'あるの',
    reading: 'アルノ',
    pronunciation: 'アルノ'
  },
  {
    word_id: 22680,
    word_type: 'KNOWN',
    word_position: 49,
    surface_form: 'まじで',
    pos: '助動詞+助動詞',
    pos_detail_1: '*',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '文語・マジ',
    conjugated_form: '基本形',
    basic_form: 'まじ',
    reading: 'マジ',
    pronunciation: 'マジ'
  },
  {
    word_id: 505510,
    word_type: 'KNOWN',
    word_position: 52,
    surface_form: 'やばいな',
    pos: '形容詞+助詞',
    pos_detail_1: '自立',
    pos_detail_2: '*',
    pos_detail_3: '*',
    conjugated_type: '形容詞・アウオ段',
    conjugated_form: '基本形',
    basic_form: 'やばい',
    reading: 'ヤバイ',
    pronunciation: 'ヤバイ'
  },
]